import { useState } from 'react';
import { Archive, BookOpenCheck, Boxes, CalendarDays, Feather, GitBranch, Lightbulb, Plus, UserRound } from 'lucide-react';
import { api } from '../api/client';
const modules = [['Historias', 'Crea, publica, archiva y duplica manuscritos.', Feather], ['Capítulos', 'Ordena escenas, borradores y publicaciones.', BookOpenCheck], ['Arcos', 'Estructura el viaje narrativo por ciclos.', GitBranch], ['Volúmenes', 'Agrupa capítulos como entregas editoriales.', Archive], ['Personajes', 'Fichas vivas, roles, habilidades y relaciones.', UserRound], ['Eventos', 'Cronología, importancia, etiquetas y vínculos.', CalendarDays], ['Ideas', 'Notas privadas, giros y semillas pendientes.', Lightbulb], ['Ítems', 'Objetos, inventario y símbolos recurrentes.', Boxes]];
export default function WriterStudio() {
  const [form, setForm] = useState({ title: '', description: '', coverImageUrl: '', visibilityState: 'public', publicationState: 'draft', allowFeedback: true, allowScores: true });
  const [message, setMessage] = useState('');
  async function createStory(event) { event.preventDefault(); setMessage(''); try { const result = await api.stories.create({ ...form, startedOn: new Date().toISOString().slice(0, 10) }); setMessage(`Historia creada: ${result.title || form.title}`); setForm({ ...form, title: '', description: '', coverImageUrl: '' }); } catch (error) { setMessage(error.message || 'No se pudo crear la historia.'); } }
  return <section className="page studio-page"><div className="section-heading wide"><span className="eyebrow">Estudio del escritor</span><h1>Un escritorio narrativo para construir mundos completos.</h1><p>Preparado para crear historias y trabajar después con capítulos, arcos, volúmenes, personajes, eventos, ideas e ítems.</p></div><div className="studio-layout"><form className="editorial-card create-panel" onSubmit={createStory}><h2>Nueva historia</h2><label>Título<input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} required /></label><label>Portada URL<input value={form.coverImageUrl} onChange={(e) => setForm({ ...form, coverImageUrl: e.target.value })} /></label><label>Sinopsis<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} rows="5" /></label><div className="two-cols"><label>Visibilidad<select value={form.visibilityState} onChange={(e) => setForm({ ...form, visibilityState: e.target.value })}><option value="public">Pública</option><option value="private">Privada</option></select></label><label>Estado<select value={form.publicationState} onChange={(e) => setForm({ ...form, publicationState: e.target.value })}><option value="draft">Borrador</option><option value="published">Publicada</option></select></label></div><button className="btn primary"><Plus size={17} /> Crear historia</button>{message && <p className="form-message">{message}</p>}</form><div className="module-grid">{modules.map(([title, text, Icon]) => <div className="module-card" key={title}><Icon size={22} /><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>;
}
